# Generated by Django 3.2.7 on 2021-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210911_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event',
            field=models.BooleanField(default=True),
        ),
    ]
