# Generated by Django 3.2.7 on 2021-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event_is_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
