# Generated by Django 3.2.7 on 2021-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_event_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='destination',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
